title: Kangzhi Zhao's Homepage
page-top-title: Kangzhi Zhao
top-section-bg-text: Be what you wanna be
home-subtitle: Kangzhi Zhao&ensp;|&ensp;赵康志
copyright-text: '&copy; Kangzhi Zhao 2023-2025. All Rights Reserved.'
